Repository Ureca-Final-Project-Team2/fe_badata, pull requests merged in 2025-08, with the labels that each got.

#230 Feat: [BADA-333] 게시물 전체 조회, 마감임박 게시물 조회 API 응답 프로퍼티명 변경
  src/entities/trade-post/api/apis.ts
  src/features/trade/api/apis.ts
Labels: 📬 API

#233 Feat: [BADA-332] PWA 알림 설정
  next.config.ts
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  src/app/layout.tsx
  src/app/manifest.json
  src/components/FCMLoader.tsx
  src/shared/hooks/useFCM.ts
  src/shared/lib/firebase.ts
Labels: ✨ Feature, 🎨 UI Design

#239 Fix: [BADA-332] 백그라운드 중복 알림 수정
  public/firebase-messaging-sw.js
  src/shared/hooks/useFCM.ts
Labels: 🎨 UI Design, 🐞 BugFix

#238 Feat: [BADA-336] 마이 페이지 구매내역 기프티콘 상세페이지 UI, API 연동
  src/app/api/proxy-image/route.ts
  src/app/mypage/purchase-history/gifticon-detail/page.tsx
  src/entities/user/api/apis.ts
  src/entities/user/lib/types.ts
  src/entities/user/model/queries.ts
  src/features/mypage/purchase-history/gifticon-detail/hooks/useReportStatus.ts
  src/features/mypage/purchase-history/gifticon-detail/page/PurchasedGifticonDetailPage.tsx
  src/features/mypage/purchase-history/gifticon-detail/ui/GifticonViewModal.tsx
  src/features/mypage/purchase-history/gifticon-detail/ui/PurchasedGifticonDetailSkeleton.tsx
  src/features/mypage/purchase-history/gifticon-detail/ui/ReportModal.tsx
  src/features/mypage/purchase-history/page/PurchaseHistoryPage.tsx
  src/shared/api/endpoints.ts
  src/shared/lib/formatDate.ts
  src/shared/lib/proxyImageDownload.ts
  src/shared/ui/SectionDivider/SectionDivider.tsx
  src/shared/ui/UserAvatar/UserAvatar.tsx
Labels: ✨ Feature, 📬 API, 🎨 UI Design, 🔨 Refactor

#235 Feat: [BADA-330] 거래 판매자 페이지 UI, API 연동
  src/app/trade/seller/[userId]/page.tsx
  src/entities/trade-post/api/apis.ts
  src/entities/trade-post/lib/types.ts
  src/entities/trade-post/model/mutations.ts
  src/entities/trade-post/model/queries.ts
  src/entities/user/api/apis.ts
  src/entities/user/lib/types.ts
  src/entities/user/model/mutations.ts
  src/entities/user/model/queries.ts
  src/features/trade/data/detail/page/DataDetailPage.tsx
  src/features/trade/gifticon/detail/page/GifticonDetailPage.tsx
  src/features/trade/seller/page/SellerPage.tsx
  src/shared/api/endpoints.ts
  src/shared/ui/Switch/Switch.tsx
  src/widgets/trade/post-detail/ui/TradeDetailSellerSection.tsx
  src/widgets/user/ui/UserProfileCard.tsx
Labels: ✨ Feature, 📬 API, 🎨 UI Design, 🔨 Refactor

#245 Feature/bada 321 current pos
  public/assets/spinner.gif
  public/firebase-messaging-sw.js
  src/app/globals.css
  src/app/layout.tsx
  src/app/mypage/purchase-history/gifticon-detail/page.tsx
  src/app/rental/page.tsx
  src/features/rental/map/api/apis.ts
  src/features/rental/map/components/OceanWaveMarker.module.css
  src/features/rental/map/components/OceanWaveMarker.tsx
  src/features/rental/map/components/index.ts
  src/features/rental/map/hooks/useCurrentLocationMarkerHooks.ts
  src/features/rental/map/hooks/useDrawerStaterHooks.ts
  src/features/rental/map/hooks/useFetchStoresHooks.ts
  src/features/rental/map/hooks/useFilterStaterHooks.ts
  src/features/rental/map/hooks/useKakaoMapHooks.ts
  src/features/rental/map/hooks/useLocationHooks.ts
  src/features/rental/map/hooks/useMapZoomLevel.ts
  src/features/rental/map/hooks/useMarkerRenderingrHooks.ts
  src/features/rental/map/hooks/useSelectedStore.ts
  src/features/rental/map/hooks/useSelectedStorerHooks.ts
  src/features/rental/map/hooks/useUrlParamsrHooks.ts
  src/features/rental/map/hooks/useUserLocationrHooks.ts
  src/features/rental/map/lib/clusterMarker.ts
  src/features/rental/map/lib/currentLocationMarker.ts
  src/features/rental/map/lib/dropletMarker.ts
  src/features/rental/map/lib/markerCache.ts
  src/features/rental/map/lib/markerCreator.ts
  src/features/rental/map/lib/markerEventHandlers.ts
  src/features/rental/map/lib/placeMarker.ts
  src/features/rental/map/lib/renderStoreMarkers.ts
  src/features/rental/map/lib/types/marker.ts
  src/features/rental/map/page/RentalPage.tsx
  src/features/rental/map/ui/DeviceCard.tsx
  src/features/rental/map/ui/DeviceImage.tsx
  src/features/rental/map/ui/DragBottomSheet.tsx
  src/features/rental/map/ui/MapSection.tsx
  src/features/rental/map/ui/RentalSortFilter.tsx
  src/features/rental/map/ui/SortDrawer.tsx
  src/features/rental/map/ui/StoreCard.tsx
  src/features/rental/map/utils/filterParamsMapper.ts
  src/features/rental/search/hook/useGetAddressHistoryInfiniteHooks.ts
  src/features/rental/search/page/SearchPosPage.tsx
  src/features/rental/store/reservation/page/ReservationPage.tsx
  src/features/rental/store/reservation/ui/CalendarSection.tsx
  src/features/rental/store/reservation/ui/ReservationForm.tsx
  src/features/rental/store/reservation/utils/typeConverters.ts
  src/features/rental/store/store-detail/page/StoreDetailPage.tsx
  src/features/rental/store/store-detail/ui/ContentSection.tsx
  src/shared/config/iconPath.ts
  src/shared/lib/utils/storeIsOpeningUtils.ts
  src/shared/ui/BaseLayout.tsx
  src/shared/ui/ImageBox/ImageBox.tsx
  src/shared/ui/Loading/Loading.tsx
  src/shared/ui/Loading/index.ts
  src/shared/ui/Spinner/Spinner.tsx
  src/shared/ui/Spinner/index.ts
Labels: ✨ Feature, 🎨 UI Design, 🐞 BugFix, 🔨 Refactor

#247 Feat: [BADA-320] 거래 추천 페이지 구현
  public/images/background-ocean.png
  public/images/lock.png
  public/images/swiper.png
  src/app/page.tsx
  src/app/recommend/page.tsx
  src/features/trade/_client/TradePageClient.tsx
  src/features/trade/recommendation/api/apis.ts
  src/features/trade/recommendation/lib/types.ts
  src/features/trade/recommendation/model/mutations.ts
  src/features/trade/recommendation/model/queries.ts
  src/features/trade/recommendation/model/useSwipeRecommendationState.ts
  src/features/trade/recommendation/page/SwipeRecommendationPage.tsx
  src/features/trade/recommendation/ui/Bubble.tsx
  src/features/trade/recommendation/ui/OceanBackground.tsx
  src/features/trade/recommendation/ui/ProgressBar.tsx
  src/features/trade/recommendation/ui/StatsCard.tsx
  src/features/trade/recommendation/ui/SwiperCard.tsx
  src/features/trade/ui/TradeRecommendPostsSection.tsx
  src/shared/api/endpoints.ts
  src/shared/config/iconPath.ts
  src/shared/config/path.ts
  src/shared/ui/BottomNav/BottomNav.tsx
Labels: ✨ Feature, 📬 API, 🎨 UI Design, 🔨 Refactor

#258 Feat: [BADA-367] 추천 게시물 튜토리얼 추가
  src/entities/auth/model/authStore.ts
  src/features/trade/recommendation/page/SwipeRecommendationPage.tsx
  src/features/trade/recommendation/ui/SwipeTutorialOverlay.tsx
  src/features/trade/recommendation/ui/SwiperCard.tsx
  src/shared/assets/SwiperLeft.json
  src/shared/assets/SwiperRight.json
Labels: ✨ Feature, 🎨 UI Design, 🔨 Refactor

#262 Feat: [BADA-370] 메타데이터 적용 및 UI 개선
  public/assets/og-image.png
  public/favicon.ico
  src/app/favicon.ico
  src/app/layout.tsx
  src/features/trade/recommendation/ui/SwipeTutorialOverlay.tsx
Labels: ✨ Feature, 🎨 UI Design, 🥰 Accessibility

#260 Feat: [BADA-369] 게시물 검색 안되는 문제 해결
  src/features/trade/search-post/api/apis.ts
  src/shared/lib/axios/axiosInterceptor.ts
Labels: 📬 API, 🐞 BugFix, 🔨 Refactor

#264 Feat: [BADA-371] onboarding qa
  src/app/page.tsx
  src/features/onboarding/ui/slides/Slide1.tsx
  src/features/onboarding/ui/slides/Slide2.tsx
  src/features/onboarding/ui/slides/Slide3.tsx
  src/features/onboarding/ui/slides/Slide4.tsx
Labels: ✨ Feature, 🐞 BugFix

#270 Fix: [BADA-371] WelcomePage 건너뛰기 클릭 시 LocationPermission으로 이동
  src/app/onboarding/page.tsx
Labels: 🐞 BugFix

#280 Feat: [BADA-381] 전반적인 코드 리팩토링
  public/assets/gifticon/ott-music/bg/NETFLIX_Logo.svg
  src/app/mypage/page.tsx
  src/entities/follow/api/apis.ts
  src/entities/follow/model/queries.ts
  src/entities/follow/ui/FollowListPage.tsx
  src/entities/trade-post/api/apis.ts
  src/entities/trade-post/model/mutations.ts
  src/entities/trade-post/model/useTradePostLikeHooks.ts
  src/entities/user/model/queries.ts
  src/features/mypage/coin-history/api/apis.ts
  src/features/mypage/coin-history/page/CoinHistoryPage.tsx
  src/features/mypage/follower/api/apis.ts
  src/features/mypage/following/api/apis.ts
  src/features/mypage/like-store/page/LikeStorePage.tsx
  src/features/mypage/like-trade-post/page/LikeTradePostPage.tsx
  src/features/mypage/purchase-history/gifticon-detail/hooks/useReportStatus.ts
  src/features/mypage/purchase-history/gifticon-detail/ui/GifticonViewModal.tsx
  src/features/mypage/purchase-history/page/PurchaseHistoryPage.tsx
  src/features/mypage/rental-history/page/RentalHistoryPage.tsx
  src/features/mypage/report-history/page/ReportHistoryPage.tsx
  src/features/mypage/restock-alarm/model/queries.ts
  src/features/mypage/restock-alarm/page/RestockAlarmPage.tsx
  src/features/mypage/sales-history/page/SalesHistoryPage.tsx
  src/features/mypage/ui/AlarmNoticeSection.tsx
  src/features/mypage/ui/AlarmSettingSection.tsx
  src/features/mypage/ui/RentalSection.tsx
  src/features/mypage/ui/SosSection.tsx
  src/features/mypage/ui/TradeSection.tsx
  src/features/onboarding/ui/IntroVideo.tsx
  src/features/rental/store/register-review/ui/ReviewRegisterForm.tsx
  src/features/trade/data/detail/api/apis.ts
  src/features/trade/deadline/page/DeadlinePage.tsx
  src/features/trade/gifticon/ui/GifticonFilterDrawer.tsx
  src/features/trade/recommendation/model/mutations.ts
  src/features/trade/register/data/model/mutations.ts
  src/features/trade/register/data/ui/DataEditForm.tsx
  src/features/trade/register/data/ui/DataRegisterForm.tsx
  src/features/trade/register/data/ui/MobileCarrierSelect.tsx
  src/features/trade/register/gifticon/api/apis.ts
  src/features/trade/register/gifticon/ui/GifticonEditForm.tsx
  src/features/trade/register/gifticon/ui/GifticonRegisterForm.tsx
  src/features/trade/report/page/ReportPage.tsx
  src/features/trade/seller/page/SellerPage.tsx
  src/shared/config/brandMapping.ts
  src/shared/config/errorCodes.ts
  src/shared/config/iconPath.ts
  src/shared/lib/getPartnerDefaultImage.ts
  src/shared/lib/makeToast.tsx
  src/shared/ui/EmptyState/EmptyState.tsx
  src/shared/ui/InAppNotification.tsx
  src/widgets/data-usage/api/apis.ts
  src/widgets/data-usage/ui/DataUsageWidgetContainer.tsx
  src/widgets/trade/payment/model/usePayment.ts
  src/widgets/trade/post-detail/ui/TradeDetailDrawer.tsx
  src/widgets/trade/post-detail/ui/TradeDetailSellerSection.tsx
  src/widgets/trade/ui/TradePostCard.tsx
  src/widgets/user/model/useFollowState.ts
Labels: 🎨 UI Design, 🔨 Refactor

#285 Feat: [BADA-379] SOS_2차 QA
  src/shared/config/iconPath.ts
  src/widgets/sos/api/apis.ts
  src/widgets/sos/model/useSseSosListener.ts
  src/widgets/sos/ui/SosDrawer.tsx
  src/widgets/sos/ui/SosModal.tsx
  src/widgets/sos/ui/makeCustomToast.tsx
Labels: ✨ Feature, 🎨 UI Design, 🔨 Refactor
