Repository Ureca-Final-Project-Team2/fe_badata, pull requests merged in 2025-07, with the labels that each got.

#14 Feat: [BADA-69] Tailwind v4 기반 전역 스타일 및 폰트 설정
  src/app/globals.css
  src/app/layout.tsx
  src/styles/font.css
  src/styles/global.css
  src/styles/index.css
Labels: ⚙ Setting, ✨ Feature

#15 Feat: [BADA-69] tailwind.config.ts 추가 (색상 토큰, fontSize)
  src/app/layout.tsx
  tailwind.config.ts
Labels: ⚙ Setting

#20 Feat: [BADA-69] Storybook Webpack 설정 및 addon 버전 충돌 해결
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  eslint.config.mjs
  package-lock.json
  package.json
  postcss.config.js
  postcss.config.mjs
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: ⚙ Setting, ✨ Feature

#25 Fix: [BADA-73] npm run dev 해결 #19
  src/app/globals.css
  src/app/layout.tsx
  src/shared/styles/font.css
  src/shared/styles/global.css
  src/shared/styles/index.css
Labels: 🐞 BugFix

#27 Refactor: [BADA-77] Storybook vite 기반으로 변경 #26
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: 🔨 Refactor

#28 Feat: [BADA-73] 공통 컴포넌트 및 스토리북 구현_게시물, 좋아요 버튼, 이미지박스
  package-lock.json
  package.json
  public/assets/sample.png
  src/components/ui/button.tsx
  src/features/imageCard/hooks/useImageCard.ts
  src/features/like/hooks/useLike.ts
  src/lib/utils.ts
  src/shared/components/ui/ImageBox/ImageBox.stories.tsx
  src/shared/components/ui/ImageBox/ImageBox.tsx
  src/shared/components/ui/ImageBox/index.ts
  src/shared/components/ui/ImageCard/ImageCard.stories.tsx
  src/shared/components/ui/ImageCard/ImageCard.tsx
  src/shared/components/ui/ImageCard/index.ts
  src/shared/components/ui/LikeButton/LikeButton.stories.tsx
  src/shared/components/ui/LikeButton/LikeButton.tsx
  src/shared/components/ui/LikeButton/index.ts
Labels: 🎨 UI Design

#30 Feat: [BADA-74] 공통 컴포넌트 및 스토리북 구현_헤더, 바텀네비게이션, date picker, input field
  components.json
  public/BADATA.svg
  public/SOS.svg
  src/app/globals.css
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/popover.tsx
  src/shared/components/ui/BottomNav/BottmNav.stories.tsx
  src/shared/components/ui/BottomNav/BottomNav.tsx
  src/shared/components/ui/BottomNav/index.ts
  src/shared/components/ui/DatePicker/DatePicker.stories.tsx
  src/shared/components/ui/DatePicker/DatePicker.tsx
  src/shared/components/ui/DatePicker/index.ts
  src/shared/components/ui/Header/Header.stories.tsx
  src/shared/components/ui/Header/Header.tsx
  src/shared/components/ui/Header/PageHeader.stories.tsx
  src/shared/components/ui/Header/PageHeader.tsx
  src/shared/components/ui/Header/index.ts
  src/shared/components/ui/InputField/InputField.stories.tsx
  src/shared/components/ui/InputField/InputField.tsx
  src/shared/components/ui/InputField/InputField.types.ts
  src/shared/components/ui/InputField/InputField.variants.ts
  src/shared/components/ui/InputField/index.ts
  src/shared/components/ui/LoginButton/LoginButton.stories.tsx
  src/shared/components/ui/LoginButton/LoginButton.tsx
  src/shared/components/ui/LoginButton/index.ts
  src/shared/components/ui/TextAreaField/TextAreaField.stories.tsx
  src/shared/components/ui/TextAreaField/TextAreaField.tsx
  src/shared/components/ui/TextAreaField/index.ts
  src/shared/lib/cn.ts
  src/stories/Configure.mdx
Labels: ✨ Feature, 🎨 UI Design

#31 Feat: [BADA-76] 공통 컴포넌트 및 스토리북 구현_배지, 플로팅버튼, 스위치, drawer
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/vitest.setup.ts
  package.json
  src/components/ui/badge.tsx
  src/components/ui/switch.tsx
  src/lib/utils.ts
  src/shared/components/ui/Badge/Badge.stories.tsx
  src/shared/components/ui/Badge/Badge.tsx
  src/shared/components/ui/Badge/index.ts
  src/shared/components/ui/Drawer/Drawer.stories.tsx
  src/shared/components/ui/Drawer/Drawer.tsx
  src/shared/components/ui/Drawer/DrawerButton.tsx
  src/shared/components/ui/Drawer/index.ts
  src/shared/components/ui/FilterDrawer/FilterDrawer.stories.tsx
  src/shared/components/ui/FilterDrawer/FilterDrawer.tsx
  src/shared/components/ui/FilterDrawer/FilterDrawerButton.tsx
  src/shared/components/ui/FilterDrawer/index.ts
  src/shared/components/ui/FloatingActionButton/FloatingActionButtion.stories.tsx
  src/shared/components/ui/FloatingActionButton/FloatingActionButton.tsx
  src/shared/components/ui/FloatingActionButton/index.ts
  src/shared/components/ui/Switch/Switch.stories.tsx
  src/shared/components/ui/Switch/Switch.tsx
  src/shared/components/ui/Switch/index.ts
  vitest.config.ts
  vitest.shims.d.ts
Labels: 🎨 UI Design

#37 Feat: [BADDA-73] 공통 컴포넌트_거래 게시물 부분
  package.json
  src/components/ui/button.tsx
  src/lib/cn.ts
  src/shared/components/ui/ImageBox/ImageBox.stories.tsx
  src/shared/components/ui/ImageBox/ImageBox.tsx
  src/shared/components/ui/Product/Product.stories.tsx
  src/shared/components/ui/Product/Product.tsx
  src/shared/components/ui/Product/indext.ts
  src/shared/components/ui/ProductInfo/ProductInfo.stories.tsx
  src/shared/components/ui/ProductInfo/ProductInfo.tsx
  src/shared/components/ui/ProductInfo/index.ts
  src/shared/lib/utils.ts
Labels: 🎨 UI Design

#40 Feat: [BADA-87] BaseLayout 컴포넌트 추가 및 모바일 웹 구조 개선
  src/app/globals.css
  src/app/layout.tsx
  src/shared/components/layout/BaseLayout.tsx
  src/shared/components/ui/BottomNav/BottomNav.tsx
Labels: ✨ Feature, 🎨 UI Design

#45 Feat: [BADA-85] 거래 상세페이지 UI
  .storybook/main.ts
  package-lock.json
  public/assets/trade_detail.jpg
  src/app/trade/[id]/page.tsx
  src/components/ui/button.tsx
  src/features/trade/components/TradeDetailProductSection.tsx
  src/features/trade/components/TradeDetailSellerSection.tsx
  src/features/trade/pages/TradeDetailPage.tsx
  src/shared/components/ui/BuyButton/BuyButton.tsx
  src/shared/components/ui/Profile/Profile.tsx
Labels: ✨ Feature, 🎨 UI Design, 🔨 Refactor

#50 Feat: [BADA-104] 마이페이지 메인 화면 UI 구현 및 iconPath 설정
  package-lock.json
  package.json
  public/icons/coin.png
  public/icons/logo-badata.svg
  public/icons/logo-sos.svg
  public/icons/notification.png
  public/icons/rental-like-shop.png
  public/icons/rental-list.png
  public/icons/rental-notification.png
  public/icons/sos-siren.png
  public/icons/trade-buy-list.png
  public/icons/trade-cell-list.png
  public/icons/trade-like-list.png
  src/app/mypage/page.tsx
  src/constants/iconPath.ts
  src/features/mypage/components/MyDataUsageCard.tsx
  src/features/mypage/components/MyPageHeader.tsx
  src/features/mypage/components/MyRentalSection.tsx
  src/features/mypage/components/MyReportStatus.tsx
  src/features/mypage/components/MySettings.tsx
  src/features/mypage/components/MySosSection.tsx
  src/features/mypage/components/MyTradeSection.tsx
  src/shared/components/ui/BottomNav/BottomNav.tsx
  src/shared/components/ui/Header/Header.tsx
Labels: ✨ Feature, 🎨 UI Design

#52 Feat: [BADA-107] 대여_카카오 지도에 가맹점 표시하기
  src/app/rental/page.tsx
  src/features/auth/apis/auth.ts
  src/features/auth/models/user.ts
  src/features/auth/stores/authStore.ts
  src/features/stores/map/apis/map.ts
  src/features/stores/map/hooks/useFetchStores.ts
  src/features/stores/map/hooks/useKakaoMap.ts
  src/features/stores/map/types/fetchParams.ts
  src/features/stores/map/types/index.ts
  src/features/stores/map/types/store.ts
  src/features/stores/map/utils/renderStoreMarkers.ts
  src/shared/components/ui/Product/indext.ts
  src/shared/constants/api.ts
  src/shared/lib/axios/axiosInstance.ts
  src/shared/lib/axios/axiosInterceptor.ts
  src/shared/lib/axios/errorHandler.ts
  src/shared/lib/axios/models.ts
  src/shared/lib/axiosInterceptor.ts
  src/shared/types/api.ts
  src/shared/utils/buildQueryParams.ts
  src/shared/utils/formatDate.ts
  tsconfig.json
Labels: ✨ Feature, 📬 API

#55 Feat: [BADA-110] 거래 메인, 데이터, 쿠폰 탭 페이지 UI 구현 및 API 연동
  src/app/layout.tsx
  src/app/trade/coupon/page.tsx
  src/app/trade/data/page.tsx
  src/app/trade/page.tsx
  src/features/trade/apis/trade.ts
  src/features/trade/components/TradeCouponFilter.tsx
  src/features/trade/components/TradeCouponList.tsx
  src/features/trade/components/TradeDataList.tsx
  src/features/trade/components/TradeMainBanner.tsx
  src/features/trade/components/TradeMainList.tsx
  src/features/trade/components/TradePageHeader.tsx
  src/features/trade/components/banner/TradeDeadlineBanner.tsx
  src/features/trade/models/post.ts
  src/features/trade/pages/TradeCouponPage.tsx
  src/features/trade/pages/TradeDataPage.tsx
  src/features/trade/pages/TradeMainPage.tsx
  src/features/trade/queries/useTradeQuery.ts
  src/shared/components/ui/Product/Product.tsx
  src/shared/components/ui/ProductInfo/ProductInfo.tsx
  src/shared/constants/api.ts
  src/shared/constants/errorCodes.ts
Labels: ✨ Feature, 📬 API, 🎨 UI Design

#58 Fix: [BADA-122] 소셜 로그인 accessToken undefined 에러_axiosIntercepter 예외처리
  src/features/auth/logics/useKakaoCallback.ts
  src/shared/lib/axios/axiosInterceptor.ts
Labels: 🐞 BugFix

#59 Feat: [BADA-105] 거래 상세 페이지 UI 수정 및 API 연결
  src/app/trade/[id]/page.tsx
  src/app/trade/coupon/[id]/page.tsx
  src/app/trade/data/[id]/page.tsx
  src/features/auth/hooks/useIsPostOwner.ts
  src/features/auth/models/user.ts
  src/features/trade/apis/trade.ts
  src/features/trade/components/TradeDetailSellerSection.tsx
  src/features/trade/components/detail/TradeDetailDrawer.tsx
  src/features/trade/components/detail/TradeDetailProductSection.tsx
  src/features/trade/components/detail/TradeDetailSellerSection.tsx
  src/features/trade/models/post.ts
  src/features/trade/pages/TradeDetailPage.tsx
  src/features/trade/queries/useTradeQuery.ts
  src/features/trade/queries/useUserTradePostQuery.ts
  src/shared/components/ui/BottomNav/BottomNav.tsx
  src/shared/components/ui/Drawer/Drawer.tsx
  src/shared/components/ui/Header/PageHeader.tsx
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#67 Feat: [BADA-119] 거래 검색 페이지 UI, ESLint 설정 변경
  eslint.config.mjs
  src/app/trade/coupon/[id]/page.tsx
  src/app/trade/data/[id]/page.tsx
  src/app/trade/search/page.tsx
  src/features/trade/api/trade.ts
  src/features/trade/lib/types.ts
  src/features/trade/model/useTradeQueries.ts
  src/features/trade/model/useUserTradePostQuery.ts
  src/features/trade/pages/TradeCouponPage.tsx
  src/features/trade/pages/TradeDataPage.tsx
  src/features/trade/pages/TradeDetailPage.tsx
  src/features/trade/pages/TradeMainPage.tsx
  src/features/trade/pages/TradeSearchPage.tsx
  src/features/trade/ui/TradeCouponFilter.tsx
  src/features/trade/ui/TradeCouponList.tsx
  src/features/trade/ui/TradeDataList.tsx
  src/features/trade/ui/TradePageHeader.tsx
  src/features/trade/ui/banner/TradeDeadlineBanner.tsx
  src/features/trade/ui/detail/TradeDetailDrawer.tsx
  src/features/trade/ui/detail/TradeDetailProductSection.tsx
  src/features/trade/ui/detail/TradeDetailSellerSection.tsx
  src/features/trade/ui/search/SearchHeader.tsx
  src/features/trade/ui/search/SearchHotKeywords.tsx
  src/features/trade/ui/search/SearchRecentKeywords.tsx
  src/features/trade/ui/search/SearchResult.tsx
  src/shared/components/ui/Badge/Badge.stories.tsx
  src/shared/components/ui/Badge/Badge.tsx
  src/shared/constants/path.ts
Labels: ⚙ Setting, ✨ Feature, 🎨 UI Design

#73 Feat: [BADA-142] 공통 컴포넌트 경로 수정
  src/shared/components/ui/Badge/Badge.stories.tsx
  src/shared/components/ui/Badge/Badge.tsx
  src/shared/components/ui/BottomNav/BottmNav.stories.tsx
  src/shared/components/ui/BottomNav/BottomNav.tsx
  src/shared/components/ui/BuyButton/BuyButton.stories.tsx
  src/shared/components/ui/BuyButton/BuyButton.tsx
  src/shared/components/ui/DataUsageCard/DataUsageCard.stories.tsx
  src/shared/components/ui/DataUsageCard/DataUsageCard.tsx
  src/shared/components/ui/DatePicker/DatePicker.stories.tsx
  src/shared/components/ui/DatePicker/DatePicker.tsx
  src/shared/components/ui/Drawer/Drawer.stories.tsx
  src/shared/components/ui/Drawer/Drawer.tsx
  src/shared/components/ui/Drawer/DrawerButton.tsx
  src/shared/components/ui/Drawer/FilterDrawerButton.tsx
  src/shared/components/ui/FlatTab/FlatTab.stories.tsx
  src/shared/components/ui/FlatTab/FlatTab.tsx
  src/shared/components/ui/FlatTab/types.ts
  src/shared/components/ui/FlatTab/useFlatTab.ts
  src/shared/components/ui/FloatingActionButton/FloatingActionButtion.stories.tsx
  src/shared/components/ui/FloatingActionButton/FloatingActionButton.tsx
  src/shared/components/ui/Header/Header.stories.tsx
  src/shared/components/ui/Header/Header.tsx
  src/shared/components/ui/Header/PageHeader.stories.tsx
  src/shared/components/ui/ImageBox/ImageBox.stories.tsx
  src/shared/components/ui/ImageBox/ImageBox.tsx
  src/shared/components/ui/ImageCard/ImageCard.stories.tsx
  src/shared/components/ui/ImageCard/ImageCard.tsx
  src/shared/components/ui/InputField/InputField.stories.tsx
  src/shared/components/ui/InputField/InputField.tsx
  src/shared/components/ui/LikeButton/LikeButton.stories.tsx
  src/shared/components/ui/LikeButton/LikeButton.tsx
  src/shared/components/ui/LoginButton/LoginButton.stories.tsx
  src/shared/components/ui/Product/Product.stories.tsx
  src/shared/components/ui/Product/Product.tsx
  src/shared/components/ui/ProductInfo/ProductInfo.stories.tsx
  src/shared/components/ui/ProductInfo/ProductInfo.tsx
  src/shared/components/ui/Profile/Profile.stories.tsx
  src/shared/components/ui/Profile/Profile.tsx
  src/shared/components/ui/Review/ReviewCard.stories.tsx
  src/shared/components/ui/Review/ReviewCard.tsx
  src/shared/components/ui/SectionDivider/SectionDivider.examples.stories.tsx
  src/shared/components/ui/SectionDivider/SectionDivider.stories.tsx
  src/shared/components/ui/SectionDivider/SectionDivider.tsx
  src/shared/components/ui/Slider/Slider.stories.tsx
  src/shared/components/ui/Slider/Slider.tsx
  src/shared/components/ui/Switch/Switch.stories.tsx
  src/shared/components/ui/Switch/Switch.tsx
  src/shared/components/ui/TextAreaField/TextAreaField.stories.tsx
  src/shared/components/ui/TextAreaField/TextAreaField.tsx
Labels: ✨ Feature, 🔨 Refactor

#74 Feat: [BADA-140] 가맹점 상세 조회
  src/app/rental/page.tsx
  src/features/stores/map/api/map.ts
  src/features/stores/map/lib/fetchParams.ts
  src/features/stores/map/lib/index.ts
  src/features/stores/map/lib/renderStoreMarkers.ts
  src/features/stores/map/lib/store.ts
  src/features/stores/map/model/useFetchStores.ts
  src/features/stores/map/model/useKakaoMap.ts
  src/features/stores/map/types/store.ts
  src/shared/constants/api.ts
Labels: ✨ Feature, 📬 API

#75 Feat: [BADA-138] 거래 게시물 검색 API
  src/features/trade/api/trade.ts
  src/features/trade/lib/types.ts
  src/features/trade/model/useRecentSearch.ts
  src/features/trade/model/useTradeQueries.ts
  src/features/trade/pages/TradeDetailPage.tsx
  src/features/trade/pages/TradeSearchPage.tsx
  src/features/trade/ui/TradeGifticonRegisterForm.tsx
  src/features/trade/ui/TradePageHeader.tsx
  src/features/trade/ui/detail/TradeDetailDrawer.tsx
  src/features/trade/ui/search/SearchHeader.tsx
  src/features/trade/ui/search/SearchRecentKeywords.tsx
  src/features/trade/ui/search/SearchResult.tsx
  src/features/trade/ui/search/SearchResultCard.tsx
  src/features/trade/ui/search/SearchSkeletonCard.tsx
  src/shared/components/ui/BottomNav/BottomNav.tsx
  src/shared/constants/api.ts
  src/shared/hooks/useDebounceValue.ts
  src/shared/lib/localSearch.ts
  tailwind.config.ts
Labels: ✨ Feature, 📬 API

#100 Refactor: [BADA-172] 공통 컴포넌트 리팩토링
  src/components/ui/calendar.tsx
  src/components/ui/switch.tsx
  src/shared/config/imagePath.ts
  src/shared/ui/BackIcon/BackIcon.stories.tsx
  src/shared/ui/DatePicker/DatePicker.tsx
  src/shared/ui/FlatTab/FlatTab.stories.tsx
  src/shared/ui/Header/Header.stories.tsx
  src/shared/ui/ImageBox/ImageBox.tsx
  src/shared/ui/ImageCard/ImageCard.stories.tsx
  src/shared/ui/ImageCard/ImageCard.tsx
  src/shared/ui/ImageCard/index.ts
  src/shared/ui/Product/Product.tsx
  src/shared/ui/Switch/Switch.stories.tsx
  src/shared/ui/Switch/Switch.tsx
  src/widgets/trade/ui/SellerPostCard.tsx
  src/widgets/trade/ui/TradePostCard.tsx
Labels: ✨ Feature, 🔨 Refactor

#103 Feat: [BADA-169] 대여_지도 화면 개발
  src/app/rental/page.tsx
  src/components/ui/calendar.tsx
  src/entities/devices/api/apis.ts
  src/entities/devices/lib/types.ts
  src/pages/rental/map/api/apis.ts
  src/pages/rental/map/lib/renderStoreMarkers.ts
  src/pages/rental/map/lib/types.ts
  src/pages/rental/map/model/useFetchStoresHooks.ts
  src/pages/rental/map/page/RentalPage.tsx
  src/shared/config/iconPath.ts
  src/shared/icons/filter-icon.png
  src/shared/ui/BaseLayout.tsx
  src/shared/ui/DatePicker/DatePicker.tsx
  src/shared/ui/FilterIcon/FilterIcon.stories.tsx
  src/shared/ui/FilterIcon/FilterIcon.tsx
Labels: ✨ Feature, 🎨 UI Design, 🔨 Refactor

#117 Feat: [BADA-192] 거래 게시물 등록 API 수정 및 토스트 처리
  package.json
  src/app/layout.tsx
  src/pages/trade/data/ui/DataList.tsx
  src/pages/trade/gifticon/ui/GifticonList.tsx
  src/pages/trade/register/data/lib/types.ts
  src/pages/trade/register/data/model/dataRegisterReducer.ts
  src/pages/trade/register/data/ui/DataRegisterForm.tsx
  src/pages/trade/register/data/ui/MobileCarrierSelect.tsx
  src/pages/trade/register/data/ui/TradeDataRegisterForm.tsx
  src/pages/trade/register/gifticon/api/apis.ts
  src/pages/trade/register/gifticon/lib/types.ts
  src/pages/trade/register/gifticon/model/gifticonRegisterReducer.ts
  src/pages/trade/register/gifticon/page/RegisterGifticonPage.tsx
  src/pages/trade/register/gifticon/ui/GifticonRegisterForm.tsx
  src/pages/trade/register/gifticon/ui/TradeGifticonRegisterForm.tsx
  src/shared/lib/makeToast.tsx
  src/shared/ui/Toaster/Toaster.stories.tsx
  src/shared/ui/Toaster/Toaster.tsx
  src/shared/ui/Toaster/index.ts
Labels: ✨ Feature, 🎨 UI Design, 🔨 Refactor

#122 Feature/bada 186 my trade UI
  package-lock.json
  src/app/layout.tsx
  src/app/mypage/follower/page.tsx
  src/app/mypage/following/page.tsx
  src/app/mypage/like-trade-post/page.tsx
  src/app/mypage/page.tsx
  src/app/mypage/purchase-history/page.tsx
  src/app/mypage/sales-history/page.tsx
  src/pages/mypage/alarm-setting/page/AlarmSettingPage.tsx
  src/pages/mypage/coin-history/page/CoinHistoryPage.tsx
  src/pages/mypage/follower/page/FollowerPage.tsx
  src/pages/mypage/following/page/FollowingPage.tsx
  src/pages/mypage/like-store/page/LikeStorePage.tsx
  src/pages/mypage/like-trade-post/page/LikeTradePost.tsx
  src/pages/mypage/model/useUserDataUsageQuery.ts
  src/pages/mypage/purchase-history/page/PurchaseHistoryPage.tsx
  src/pages/mypage/rental-history/page/RentalHistoryPage.tsx
  src/pages/mypage/report-history/page/ReportHistoryPage.tsx
  src/pages/mypage/restock-alarm/page/RestockAlarmPage.tsx
  src/pages/mypage/sales-history/page/SalesHistoryPage.tsx
  src/pages/mypage/sos-history/page/SosHistoryPage.tsx
  src/pages/mypage/ui/AlarmSettingSection.tsx
  src/pages/mypage/ui/DataUsageCardSection.tsx
  src/pages/mypage/ui/RentalSection.tsx
  src/pages/mypage/ui/ReportStatusSection.tsx
  src/pages/mypage/ui/SosSection.tsx
  src/pages/mypage/ui/TradeSection.tsx
  src/shared/icons/coin.png
  src/shared/ui/FlatTab/FlatTab.stories.tsx
  src/shared/ui/FlatTab/FlatTab.tsx
  src/widgets/trade/flat-tab/ui/TradePageHeader.tsx
  src/widgets/trade/ui/SellerPostCard.stories.tsx
  src/widgets/trade/ui/TradePostCard.stories.tsx
Labels: ✨ Feature, 🎨 UI Design, 🔨 Refactor

#124 Feat: [BADA-203] 가맹점 디바이스 카드 스와이프 및 마커 UX 개선
  next.config.ts
  src/app/globals.css
  src/entities/scroll/CenterScrollSwiper.tsx
  src/entities/scroll/index.ts
  src/entities/scroll/useCenterScrollIndex.tsx
  src/pages/rental/map/__mocks__/deviceCard.mock.ts
  src/pages/rental/map/lib/renderStoreMarkers.ts
  src/pages/rental/map/lib/types.ts
  src/pages/rental/map/model/selectedStoreReducer.ts
  src/pages/rental/map/model/useSelectedStore.ts
  src/pages/rental/map/page/RentalPage.tsx
  src/pages/rental/map/ui/DeviceCard.tsx
  src/pages/rental/map/ui/DeviceImage.tsx
  src/pages/rental/map/ui/MapSection.tsx
  src/pages/rental/map/ui/ReserveButton.tsx
  src/shared/styles/radius.css
Labels: ✨ Feature, 🎨 UI Design, 🔨 Refactor

#130 Feat: [BADA-201] 게시물 수정, 삭제, 팔로우 토글 API 연동, UI 수정
  package.json
  src/app/trade/register/data/edit/[postId]/page.tsx
  src/app/trade/register/gifticon/edit/[postId]/page.tsx
  src/entities/auth/model/authStore.ts
  src/entities/trade-post/api/apis.ts
  src/entities/trade-post/lib/types.ts
  src/entities/trade-post/model/mutations.ts
  src/entities/trade-post/model/queries.ts
  src/entities/user/api/apis.ts
  src/entities/user/index.ts
  src/entities/user/lib/types.ts
  src/entities/user/model/mutations.ts
  src/entities/user/model/queries.ts
  src/pages/trade/data/detail/page/DataDetailPage.tsx
  src/pages/trade/gifticon/detail/page/GifticonDetailPage.tsx
  src/pages/trade/register/data/page/DataEditPage.tsx
  src/pages/trade/register/data/ui/DataEditForm.tsx
  src/pages/trade/register/gifticon/page/GifticonEditPage.tsx
  src/pages/trade/register/gifticon/ui/GifticonEditForm.tsx
  src/shared/api/endpoints.ts
  src/shared/config/errorCodes.ts
  src/shared/lib/axios/axiosInterceptor.ts
  src/shared/ui/Drawer/Drawer.tsx
  src/shared/ui/Drawer/DrawerButton.tsx
  src/widgets/trade/post-detail/ui/TradeDetailDrawer.tsx
  src/widgets/trade/post-detail/ui/TradeDetailProductSection.tsx
  src/widgets/trade/post-detail/ui/TradeDetailSellerSection.tsx
  src/widgets/user/model/useFollowState.ts
  src/widgets/user/ui/UserProfileCard.tsx
Labels: ✨ Feature, 📬 API, 🎨 UI Design, 🔨 Refactor

#131 Feat: [BADA-214] 거래 게시물 신고 API 연동
  src/app/trade/page.tsx
  src/app/trade/report/[id]/page.tsx
  src/entities/trade-post/api/apis.ts
  src/entities/trade-post/lib/types.ts
  src/entities/trade-post/model/mutations.ts
  src/pages/trade/page/TradePage.tsx
  src/pages/trade/report/page/ReportPage.tsx
  src/shared/api/endpoints.ts
  src/shared/config/path.ts
  src/widgets/trade/post-detail/ui/TradeDetailDrawer.tsx
Labels: ✨ Feature, 📬 API, 🎨 UI Design, 🔨 Refactor

#143 Fix: [BADA-227] vercel 배포 fail 해결
  package-lock.json
  src/pages/mypage/like-store/page/LikeStorePage.tsx
  src/pages/rental/map/page/RentalPage.tsx
  src/pages/rental/map/utils/detaIl.ts
  src/pages/rental/map/utils/deviceCard.ts
  src/pages/rental/map/utils/reservationDeviceCard.ts
  src/pages/rental/map/utils/storeList.ts
  src/pages/rental/store/reservation/page/ReservationPage.tsx
  src/pages/rental/store/reservation/ui/index.ts
  src/pages/rental/store/store-detail/page/StoreDetailPage.tsx
Labels: 🐞 BugFix

#154 Feat: [BADA-239] 마이페이지 UI 수정
  src/app/mypage/page.tsx
  src/entities/data/api/apis.ts
  src/entities/data/lib/types.ts
  src/pages/mypage/coin-history/api/apis.ts
  src/pages/mypage/coin-history/lib/types.ts
  src/pages/mypage/coin-history/model/queries.ts
  src/pages/mypage/coin-history/page/CoinHistoryPage.tsx
  src/pages/mypage/ui/AlarmSettingSection.tsx
  src/pages/mypage/ui/DataUsageCardSection.tsx
  src/pages/mypage/ui/RentalSection.tsx
  src/pages/mypage/ui/ReportStatusSection.tsx
  src/pages/mypage/ui/SosSection.tsx
  src/pages/mypage/ui/TradeSection.tsx
  src/shared/config/iconPath.ts
  src/shared/icons/coin-stack.png
Labels: ✨ Feature, 🎨 UI Design, 🔨 Refactor

#147 Feat: [BADA-237] 기프티콘, 데이터 게시글 수정 API 분리에 따른 게시물 수정 관련 코드 업데이트
  src/entities/trade-post/api/apis.ts
  src/entities/trade-post/lib/types.ts
  src/entities/trade-post/model/mutations.ts
  src/pages/trade/register/data/page/DataEditPage.tsx
  src/pages/trade/register/data/ui/DataEditForm.tsx
  src/pages/trade/register/gifticon/page/GifticonEditPage.tsx
  src/pages/trade/register/gifticon/ui/GifticonEditForm.tsx
  src/shared/api/endpoints.ts
  src/shared/ui/TextAreaField/TextAreaField.tsx
Labels: ✨ Feature, 📬 API, 🎨 UI Design, 🔨 Refactor

#152 Feat: [BADA-224] 기프티콘 이미지 유효성 검사 및 OCR API 연동
  src/pages/trade/data/detail/api/apis.ts
  src/pages/trade/register/gifticon/api/apis.ts
  src/pages/trade/register/gifticon/lib/types.ts
  src/pages/trade/register/gifticon/model/gifticonRegisterReducer.ts
  src/pages/trade/register/gifticon/model/mutations.ts
  src/pages/trade/register/gifticon/ui/GifticonRegisterForm.tsx
  src/shared/api/endpoints.ts
  src/shared/lib/axios/axiosInterceptor.ts
Labels: ✨ Feature, 📬 API, 🎨 UI Design, 🔨 Refactor

#159 Feat: [BADA-249] 마이페이지 나의 찜한 게시물 글 API 연동
  src/pages/mypage/follower/api/apis.ts
  src/pages/mypage/follower/lib/types.ts
  src/pages/mypage/follower/model/queries.ts
  src/pages/mypage/follower/page/FollowerPage.tsx
  src/pages/mypage/following/api/apis.ts
  src/pages/mypage/following/lib/types.ts
  src/pages/mypage/following/model/queries.ts
  src/pages/mypage/following/page/FollowingPage.tsx
  src/pages/mypage/like-trade-post/api/apis.ts
  src/pages/mypage/like-trade-post/lib/types.ts
  src/pages/mypage/like-trade-post/model/queries.ts
  src/pages/mypage/like-trade-post/page/LikeTradePost.tsx
  src/shared/api/endpoints.ts
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#161 Feat: [BADA-247] 나의 판매 내역 조회 API 연결, UI 수정
  src/entities/user/model/queries.ts
  src/pages/mypage/sales-history/page/SalesHistoryPage.tsx
  src/shared/ui/Skeleton/Skeleton.tsx
  src/shared/ui/Skeleton/TradePostCardSkeleton.tsx
  src/shared/ui/Switch/Switch.tsx
Labels: ✨ Feature, 📬 API, 🎨 UI Design, 🔨 Refactor

#157 Feat: [BADA-246] 마이페이지 팔로잉/팔로워 API 연동
  package.json
  src/pages/mypage/follower/api/apis.ts
  src/pages/mypage/follower/model/queries.ts
  src/pages/mypage/following/api/apis.ts
  src/pages/mypage/following/model/queries.ts
  src/pages/mypage/sales-history/page/SalesHistoryPage.tsx
  src/shared/lib/axios/axiosInterceptor.ts
Labels: ✨ Feature, 📬 API, 🎨 UI Design, 🔨 Refactor

#174 Feat: [BADA-270] 마이페이지 코인 입출금 API 연동하기
  package-lock.json
  src/app/mypage/report-history/page.tsx
  src/entities/follow/model/queries.ts
  src/pages/mypage/coin-history/api/apis.ts
  src/pages/mypage/coin-history/lib/constants.ts
  src/pages/mypage/coin-history/lib/types.ts
  src/pages/mypage/coin-history/lib/utils.ts
  src/pages/mypage/coin-history/model/queries.ts
  src/pages/mypage/coin-history/page/CoinHistoryPage.tsx
  src/pages/mypage/coin-history/ui/CoinBalanceSection.tsx
  src/pages/mypage/coin-history/ui/CoinHistoryItem.tsx
  src/pages/mypage/coin-history/ui/CoinHistoryList.tsx
  src/pages/mypage/coin-history/ui/CoinInfoDrawer.tsx
  src/pages/mypage/coin-history/ui/CoinInfoModal.tsx
  src/pages/mypage/coin-history/ui/CoinUsageSection.tsx
  src/pages/mypage/coin-history/ui/ErrorBoundary.tsx
  src/pages/mypage/report-history/api/apis.ts
  src/pages/mypage/report-history/lib/types.ts
  src/pages/mypage/report-history/model/queries.ts
  src/pages/mypage/report-history/page/ReportHistoryPage.tsx
  src/pages/mypage/restock-alarm/api/apis.ts
  src/pages/mypage/restock-alarm/model/queries.ts
  src/pages/mypage/restock-alarm/page/RestockAlarmPage.tsx
  src/pages/mypage/sos-history/api/apis.ts
  src/pages/mypage/sos-history/lib/types.ts
  src/pages/mypage/sos-history/model/queries.ts
  src/pages/mypage/sos-history/page/SosHistoryPage.tsx
  src/shared/api/endpoints.ts
Labels: ✨ Feature, 📬 API, 🎨 UI Design, 🔨 Refactor

#176 Feat: [BADA-260] 렌탈 리뷰 조회 페이지 구현
  src/app/globals.css
  src/pages/rental/store/review/api/apis.ts
  src/pages/rental/store/review/lib/types.ts
  src/pages/rental/store/review/lib/utils.ts
  src/pages/rental/store/review/model/queries.ts
  src/pages/rental/store/review/page/ReviewPage.tsx
  src/pages/rental/store/review/ui/QuickReplySection.tsx
  src/pages/rental/store/review/ui/ReviewHeaderSection.tsx
  src/pages/rental/store/review/ui/ReviewItem.tsx
  src/pages/rental/store/review/ui/ReviewSortDrawer.tsx
  src/shared/api/endpoints.ts
  src/shared/ui/FilterDrawer/FilterOption.tsx
  src/shared/ui/Profile/Profile.tsx
Labels: ✨ Feature, 📬 API, 🎨 UI Design, 🔨 Refactor

#178 Feat: [BADA-266] 실시간 인기 검색어 API 연동
  src/entities/trade-post/api/apis.ts
  src/entities/trade-post/lib/types.ts
  src/pages/trade/search-post/model/queries.ts
  src/pages/trade/search-post/model/useRecentSearchHooks.ts
  src/pages/trade/search-post/page/SearchTradePage.tsx
  src/pages/trade/search-post/ui/SearchHotKeywords.tsx
  src/pages/trade/search-post/ui/SearchRecentKeywords.tsx
  src/shared/api/endpoints.ts
  src/widgets/trade/post-detail/ui/TradeDetailProductSection.tsx
Labels: ✨ Feature, 📬 API, 🎨 UI Design, 🔨 Refactor

#180 Feat: [BADA-261] 대여_위치 검색 페이지 UI 구현 및 API 연동
  src/app/rental/search-pos/page.tsx
  src/pages/rental/map/hooks/useLocationHooks.ts
  src/pages/rental/map/page/RentalPage.tsx
  src/pages/rental/map/ui/LocationDisplay.tsx
  src/pages/rental/map/ui/SearchPosHeader.tsx
  src/pages/rental/search/api/apis.ts
  src/pages/rental/search/hook/useAddressHooks.ts
  src/pages/rental/search/hook/useDeleteAddressHooks.ts
  src/pages/rental/search/hook/useGetAddressHistoryInfiniteHooks.ts
  src/pages/rental/search/hook/useSearchPlacesHooks.ts
  src/pages/rental/search/hook/useThrottledScrollHooks.ts
  src/pages/rental/search/page/AddressInfoSection.tsx
  src/pages/rental/search/page/SearchPosPage.tsx
  src/pages/rental/search/ui/AddressHistoryItem.tsx
  src/pages/rental/search/ui/AddressHistoryList.tsx
  src/pages/rental/search/ui/CurrentLocationButton.tsx
  src/pages/rental/search/ui/InfiniteScrollObserver.tsx
  src/pages/rental/search/ui/SearchInputField.tsx
  src/pages/rental/search/ui/SearchResultItem.tsx
  src/pages/rental/search/ui/SearchResults.tsx
  src/pages/rental/search/utils/address/getPosition.ts
  src/pages/rental/search/utils/address/searchPlaces.ts
  src/pages/rental/search/utils/auth/isLoggedIn.ts
  src/pages/rental/search/utils/localStorage/addressHistory.ts
  src/pages/rental/search/utils/sortUtils.ts
  src/pages/rental/utils/auth/isLoggedIn.ts
  src/shared/api/endpoints.ts
  src/shared/lib/axios/axiosInstance.ts
  src/shared/lib/axios/axiosInterceptor.ts
Labels: ✨ Feature, 📬 API, 🎨 UI Design

#184 Feat: [BADA-268] 대여 리뷰 작성 페이지 개발
  next.config.ts
  src/app/rental/store/register-review/page.tsx
  src/pages/mypage/rental-history/lib/types.ts
  src/pages/mypage/rental-history/page/RentalHistoryPage.tsx
  src/pages/rental/store/register-review/api/apis.ts
  src/pages/rental/store/register-review/lib/types.ts
  src/pages/rental/store/register-review/model/mutations.ts
  src/pages/rental/store/register-review/model/queries.ts
  src/pages/rental/store/register-review/model/reviewFormReducer.ts
  src/pages/rental/store/register-review/page/RegisterReviewPage.tsx
  src/pages/rental/store/register-review/ui/CommentSection.tsx
  src/pages/rental/store/register-review/ui/ImageUploadSection.tsx
  src/pages/rental/store/register-review/ui/QuickReplySection.tsx
  src/pages/rental/store/register-review/ui/RatingSection.tsx
  src/pages/rental/store/register-review/ui/ReservationDetailsSection.tsx
  src/pages/rental/store/register-review/ui/ReviewRegisterForm.tsx
  src/pages/rental/store/review/api/apis.ts
  src/pages/rental/store/review/ui/ReviewItem.tsx
  src/shared/api/endpoints.ts
  src/shared/config/path.ts
Labels: ✨ Feature, 📬 API, 🎨 UI Design, 🔨 Refactor

#181 Feat: [BADA-272] 마이페이지_알림 설정 API 연동
  src/components/ui/switch.tsx
  src/entities/data/model/queries.ts
  src/entities/follow/index.ts
  src/entities/user/index.ts
  src/entities/user/model/queries.ts
  src/pages/mypage/alarm-setting/api/apis.ts
  src/pages/mypage/alarm-setting/lib/constants.ts
  src/pages/mypage/alarm-setting/lib/types.ts
  src/pages/mypage/alarm-setting/model/queries.ts
  src/pages/mypage/alarm-setting/page/AlarmSettingPage.tsx
  src/pages/mypage/coin-history/lib/utils.ts
  src/pages/mypage/coin-history/page/CoinHistoryPage.tsx
  src/pages/mypage/coin-history/ui/CoinHistoryList.tsx
  src/pages/mypage/coin-history/ui/CoinInfoDrawer.tsx
  src/pages/mypage/rental-history/api/apis.ts
  src/pages/mypage/rental-history/model/queries.ts
  src/pages/mypage/report-history/api/apis.ts
  src/pages/mypage/report-history/model/queries.ts
  src/pages/mypage/sos-history/model/queries.ts
  src/pages/mypage/sos-history/page/SosHistoryPage.tsx
  src/pages/mypage/ui/AlarmSettingSection.tsx
  src/shared/lib/axios/axiosInterceptor.ts
  src/widgets/sos/ui/SosDrawer.tsx
  src/widgets/user/ui/MyProfileCard.stories.tsx
  src/widgets/user/ui/UserProfileCard.stories.tsx
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#191 Fix: [BADA-140] 2차 배포 위한 빌드 에러 해결
  src/entities/trade-post/api/apis.ts
  src/entities/trade-post/model/mutations.ts
  src/pages/mypage/follower/api/apis.ts
  src/pages/mypage/like-store/page/LikeStorePage.tsx
  src/pages/mypage/report-history/model/queries.ts
  src/pages/mypage/report-history/page/ReportHistoryPage.tsx
  src/pages/mypage/sales-history/page/SalesHistoryPage.tsx
  src/pages/rental/map/api/apis.ts
  src/pages/rental/map/hooks/useFetchStoreListHooks.ts
  src/pages/rental/map/lib/types.ts
  src/pages/rental/map/model/selectedStoreReducer.ts
  src/pages/rental/map/page/RentalPage.tsx
  src/pages/rental/map/utils/filterParamsMapper.ts
  src/pages/rental/map/utils/storeDataMapper.ts
  src/pages/rental/map/utils/storeList.ts
  src/pages/rental/store/store-detail/page/ContentSection.tsx
  src/pages/rental/store/store-detail/page/StoreDetailPage.tsx
  src/shared/api/endpoints.ts
  src/shared/lib/axios/axiosInterceptor.ts
  src/shared/ui/DatePicker/DatePicker.stories.tsx
  src/shared/ui/FilterDrawer/FilterDrawerContent.tsx
  src/shared/ui/FlatTab/types.ts
  src/shared/ui/ImageCard/ImageCard.stories.tsx
  src/widgets/trade/post-detail/ui/TradeDetailSellerSection.tsx
  src/widgets/user/ui/UserProfileCard.stories.tsx
Labels: 📬 API, 🐞 BugFix, 🔨 Refactor

#198 Feat: [BADA-289] 마이페이지_코인 상세 페이지 API 재연동
  public/images/coin.png
  src/features/api/apis.ts
  src/features/mypage/coin-history/api/apis.ts
  src/features/mypage/coin-history/lib/constants.ts
  src/features/mypage/coin-history/lib/types.ts
  src/features/mypage/coin-history/lib/utils.ts
  src/features/mypage/coin-history/model/queries.ts
  src/features/mypage/coin-history/page/CoinHistoryPage.tsx
  src/features/mypage/coin-history/ui/CoinBalanceSection.tsx
  src/features/mypage/coin-history/ui/CoinHistoryInfiniteList.tsx
  src/features/mypage/coin-history/ui/CoinHistoryItem.tsx
  src/features/mypage/coin-history/ui/CoinHistoryList.tsx
  src/features/mypage/coin-history/ui/CoinInfoDrawer.tsx
  src/features/mypage/coin-history/ui/CoinInfoModal.tsx
  src/features/mypage/coin-history/ui/CoinUsageSection.tsx
  src/features/mypage/coin-history/ui/ErrorBoundary.tsx
  src/features/mypage/like-store/model/queries.ts
  src/features/mypage/like-store/page/LikeStorePage.tsx
  src/features/mypage/sos-history/page/SosHistoryPage.tsx
Labels: ✨ Feature, 📬 API, 🎨 UI Design, 🔨 Refactor

#190 Feat: [BADA-283] 마이 페이지_userInfo 연동
  next.config.ts
  src/app/mypage/page.tsx
  src/entities/trade-post/lib/types.ts
  src/entities/user/api/apis.ts
  src/entities/user/lib/types.ts
  src/entities/user/model/mutations.ts
  src/entities/user/model/queries.ts
  src/features/mypage/purchase-history/page/PurchaseHistoryPage.tsx
  src/features/mypage/sales-history/page/SalesHistoryPage.tsx
  src/features/mypage/ui/AlarmSettingSection.tsx
  src/features/mypage/ui/RentalSection.tsx
  src/features/mypage/ui/ReportStatusSection.tsx
  src/features/mypage/ui/SosSection.tsx
  src/features/trade/data/detail/page/DataDetailPage.tsx
  src/features/trade/gifticon/detail/page/GifticonDetailPage.tsx
  src/shared/api/endpoints.ts
  src/widgets/trade/post-detail/ui/TradeDetailProductSection.tsx
  src/widgets/trade/post-detail/ui/TradeDetailSellerSection.tsx
  src/widgets/user/ui/MyProfileCard.tsx
Labels: ✨ Feature, 📬 API, 🎨 UI Design, 🔨 Refactor

#194 Fix: [BADA-298] Rental QA2
  src/app/page.tsx
  src/features/rental/map/hooks/useFetchStoreListHooks.ts
  src/features/rental/map/hooks/useFetchStoresHooks.ts
  src/features/rental/map/hooks/useLocationHooks.ts
  src/features/rental/map/hooks/useStoreListHooks.ts
  src/features/rental/map/lib/markerCache.ts
  src/features/rental/map/lib/markerCreator.ts
  src/features/rental/map/lib/markerEventHandlers.ts
  src/features/rental/map/lib/renderStoreMarkers.ts
  src/features/rental/map/lib/types.ts
  src/features/rental/map/model/useFetchStoreListHooks.ts
  src/features/rental/map/page/RentalPage.tsx
  src/features/rental/map/ui/LocationDisplay.tsx
  src/features/rental/map/ui/MapSection.tsx
  src/features/rental/map/ui/SearchPosHeader.tsx
  src/features/rental/map/utils/debounceUtils.ts
  src/features/rental/search/page/SearchPosPage.tsx
  src/shared/api/endpoints.ts
  src/shared/config/path.ts
  src/shared/ui/BaseLayout.tsx
  src/shared/ui/BottomNav/BottomNav.tsx
  src/shared/ui/Header_Detail/Header_Detail.tsx
  src/shared/ui/InputField/InputField.tsx
Labels: 📬 API, 🎨 UI Design, 🐞 BugFix, 🔨 Refactor

#200 Fix: [BADA-298] 가맹점 리스트 조회 API 해결 #192
  src/features/rental/map/api/apis.ts
Labels: 🐞 BugFix

#204 Fix: [BADA-298] rental qa2
  src/features/rental/map/ui/ReservationDeviceCard.tsx
  src/features/rental/map/utils/reservationDeviceCard.ts
  src/features/rental/store/reservation/api/apis.ts
  src/features/rental/store/reservation/ui/DeviceSelectSection.tsx
  src/features/rental/store/reservation/ui/ReservationForm.tsx
  src/features/rental/store/reservation/utils/dataFormatters.ts
Labels: 🐞 BugFix

#209 Fix: [BADA-312] TradeFloatingButton에 use client 추가
  src/widgets/trade/floating-button/ui/TradeFloatingButton.tsx
Labels: 🐞 BugFix, 🔨 Refactor

#210 Feat: [BADA-302] 거래 상세 QA 2-1
  src/app/trade/data/[id]/page.tsx
  src/features/trade/data/detail/page/DataDetailPage.tsx
  src/features/trade/gifticon/detail/page/GifticonDetailPage.tsx
  src/features/trade/search-post/ui/SearchHeader.tsx
  src/shared/ui/BuyButton/BuyButton.tsx
  src/shared/ui/BuyButton/index.ts
  src/shared/ui/CoinPaymentModal/CoinPaymentModal.tsx
  src/widgets/trade/payment/ui/BuyButtonWithPayment.tsx
  src/widgets/trade/payment/ui/PaymentReceiptModal.tsx
  src/widgets/trade/post-detail/ui/TradeDetailProductSection.tsx
  src/widgets/trade/post-detail/ui/TradeDetailSellerSection.tsx
  src/widgets/trade/ui/DetailLikeButton/DetailLikeButton.tsx
  src/widgets/trade/ui/DetailLikeButton/index.ts
  src/widgets/trade/ui/PaymentButton/PaymentButton.tsx
  src/widgets/trade/ui/PaymentButton/index.ts
  src/widgets/trade/ui/TradeActionButton/TradeActionButton.tsx
  src/widgets/trade/ui/TradeActionButton/index.ts
  src/widgets/user/ui/UserProfileCard.tsx
Labels: ✨ Feature, 🎨 UI Design, 🔨 Refactor

#211 Feat: [BADA-264] SOS_UI 구현 및 로직 구현 중
  src/app/globals.css
  src/app/mypage/page.tsx
  src/features/mypage/sos-history/page/SosHistoryPage.tsx
  src/features/mypage/ui/TradeSection.tsx
  src/features/rental/store/reservation/hooks/useReservationDevicesHooks.ts
  src/shared/lib/axios/axiosInterceptor.ts
  src/shared/ui/BaseLayout.tsx
  src/shared/ui/DataUsageCard/index.ts
  src/widgets/data-usage/DataUsageWidget.tsx
  src/widgets/data-usage/api/apis.ts
  src/widgets/data-usage/index.ts
  src/widgets/data-usage/model/queries.ts
  src/widgets/data-usage/types.ts
  src/widgets/data-usage/ui/DataUsageWidgetContainer.tsx
  src/widgets/sos/api/apis.ts
  src/widgets/sos/index.ts
  src/widgets/sos/lib/types.ts
  src/widgets/sos/lib/websocket.ts
  src/widgets/sos/model/mutations.ts
  src/widgets/sos/model/sosNotificationStore.ts
  src/widgets/sos/model/useSosWebSocket.ts
  src/widgets/sos/ui/SosDrawer.tsx
  src/widgets/sos/ui/SosExample.tsx
  src/widgets/sos/ui/SosModal.tsx
  src/widgets/sos/ui/SosNotificationHandler.tsx
  src/widgets/sos/ui/SosResponseModal.tsx
  src/widgets/sos/ui/SosTestPage.tsx
Labels: ✨ Feature, 📬 API, 🎨 UI Design, 🔨 Refactor

#216 Feature/bada 398 rental apis
  src/app/globals.css
  src/features/mypage/like-store/page/LikeStorePage.tsx
  src/features/mypage/restock-alarm/api/apis.ts
  src/features/mypage/restock-alarm/model/queries.ts
  src/features/mypage/restock-alarm/page/RestockAlarmPage.tsx
  src/features/mypage/ui/AlarmNoticeSection.tsx
  src/features/mypage/ui/DeleteConfirmModal.tsx
  src/features/rental/map/api/apis.ts
  src/features/rental/map/hooks/useFetchStoresHooks.ts
  src/features/rental/map/hooks/useKakaoMapHooks.ts
  src/features/rental/map/hooks/useLocationHooks.ts
  src/features/rental/map/hooks/useStoreListHooks.ts
  src/features/rental/map/lib/markerCache.ts
  src/features/rental/map/lib/markerCreator.ts
  src/features/rental/map/lib/types.ts
  src/features/rental/map/ui/DragBottomSheet.tsx
  src/features/rental/map/ui/MapSection.tsx
  src/features/rental/map/ui/StoreCard.tsx
  src/features/rental/map/utils/filterParamsMapper.ts
  src/features/rental/map/utils/storeDataMapper.ts
  src/shared/api/endpoints.ts
  src/shared/hooks/useStoreLikeToggle.ts
  src/shared/lib/utils/storeIsOpeningUtils.ts
  src/shared/styles/index.css
  src/shared/styles/list-animations.css
  src/shared/ui/Modal/Modal.tsx
  src/shared/ui/StoreLikeButton/StoreLikeButton.tsx
  src/shared/ui/StoreLikeButton/index.ts
Labels: ✨ Feature, 📬 API, 🎨 UI Design, 🔨 Refactor

#218 Feat: [BADA-311] 마이페이지_메인 data와 신고현황 API 연동
  src/features/mypage/report-status/api/apis.ts
  src/features/mypage/report-status/lib/types.ts
  src/features/mypage/report-status/model/queries.ts
  src/features/mypage/ui/DataUsageCardSection.tsx
  src/features/mypage/ui/ReportStatusSection.tsx
  src/shared/api/endpoints.ts
  src/widgets/data-usage/model/queries.ts
Labels: ✨ Feature, 📬 API, 🎨 UI Design, 🔨 Refactor

#213 Feat: [BADA-299] 대여 리뷰 수정/삭제 API 연동 및 기능 추가
  src/features/rental/store/register-review/_client/ReviewRegisterPageContent.tsx
  src/features/rental/store/register-review/api/apis.ts
  src/features/rental/store/register-review/lib/types.ts
  src/features/rental/store/register-review/model/mutations.ts
  src/features/rental/store/register-review/model/queries.ts
  src/features/rental/store/register-review/model/reviewFormReducer.ts
  src/features/rental/store/register-review/ui/ImageUploadSection.tsx
  src/features/rental/store/register-review/ui/ReservationDetailsSection.tsx
  src/features/rental/store/register-review/ui/ReviewRegisterForm.tsx
  src/features/rental/store/review/page/ReviewPage.tsx
  src/features/rental/store/review/ui/ReviewItem.tsx
  src/shared/config/errorCodes.ts
  src/shared/lib/axios/errorHandler.ts
Labels: ✨ Feature, 📬 API, 🎨 UI Design, 🔨 Refactor

#224 Fix: [BADA-325] userInfo 완전한 데이터 로딩 후 랜더링 되도록 수정
  src/app/mypage/page.tsx
  src/features/mypage/purchase-history/page/PurchaseHistoryPage.tsx
  src/features/mypage/sales-history/page/SalesHistoryPage.tsx
  src/shared/ui/UserAvatar/UserAvatar.tsx
  src/widgets/trade/post-detail/ui/TradeDetailSellerSection.tsx
  src/widgets/trade/ui/SellerPostCard.tsx
  src/widgets/user/ui/MyProfileCard.tsx
Labels: 📬 API, 🎨 UI Design, 🔨 Refactor
